#!/bin/bash

FILES=$(/usr/bin/find `dirname $0` -not -wholename "*.svn*" -and -name "rsnapshot-backup-*" -print);

for FILE in $FILES; do
	echo $FILE;
	cat $FILE | grep "\$WHICH" | awk '{ print substr($2, 0, length($2) - 2); }' | \
	xargs which | xargs -n 1 readlink -f | xargs dpkg -S | awk '{ print substr($1, 0, length($1) - 1); }' | \
	sort | uniq;
done
