#!/bin/sh

#
# rsnapshot-backup-debian
#
# (c) Copyright 2007 Chris Smith
# This is free software. You may redistribute copies of it under the terms of
# the GNU General Public License <http://www.opensource.org/licenses/gpl-license.php>.
# There is NO WARRANTY, to the extent permitted by law.
#
# $Id$
#
# Download latest from: $HeadURL$
#

WHICH=$(which which);

if [ "$?" != "0" ]; then
	GREP=/bin/grep
	MD5SUM=/usr/bin/md5sum
	RSYNC=/usr/bin/rsync
	SED=/bin/sed
else
	GREP=$($WHICH grep);
	MD5SUM=$($WHICH md5sum);
	RSYNC=$($WHICH rsync);
	SED=$($WHICH sed);
fi

show_usage()
{
	echo "Usage: $0 [ --version | --help ]";
	echo -e "    --help\tDisplay this help and exit";
	echo -e "    --version\tDisplay version and exit";
	exit $1;
}

show_version()
{
	echo "rsnapshot-backup-debian";
	echo '$Id$';
	echo ""
	echo "(c) Copyright 2007 Chris Smith";
	echo "This is free software. You may redistribute copies of it under the terms of";
	echo "the GNU General Public License <http://www.opensource.org/licenses/gpl-license.php>.";
	echo "There is NO WARRANTY, to the extent permitted by law.";
	echo "";
	echo "Written by Chris Smith <http://www.cs278.org/>";
	exit 0;
}

if [ "$1" = "--help" ]; then
	show_usage 0
	exit 0;
elif [ "$1" = "--version" ]; then
	show_version
	exit 0;
fi

INFO_DIR="/var/lib/dpkg/info";

cat $INFO_DIR/*.md5sums | $SED "s,  ,  /," | $MD5SUM -c | $GREP ": OK$" | $SED 's,: OK$,,' | $RSYNC --exclude-from=- / .

exit $?
