#!/bin/sh

#
# rsnapshot-backup-dpkg
#
# (c) Copyright 2007 Chris Smith
# This is free software. You may redistribute copies of it under the terms of
# the GNU General Public License <http://www.opensource.org/licenses/gpl-license.php>.
# There is NO WARRANTY, to the extent permitted by law.
#
# $Id$
#
# Download latest from: $HeadURL$
#

WHICH=$(which which);

if [ "$?" != "0" ]; then
	CHMOD=/bin/chmod;
	DPKG=/usr/bin/dpkg;
	TOUCH=/usr/bin/touch;
else
	CHMOD=$($WHICH chmod);
	DPKG=$($WHICH dpkg);
	TOUCH=$($WHICH touch);
fi

show_usage()
{
	echo "Usage: $0 [ --version | --help ]";
	echo -e "    --help\tDisplay this help and exit";
	echo -e "    --version\tDisplay version and exit";
	exit $1;
}

show_version()
{
	echo "rsnapshot-backup-dpkg";
	echo '$Id$';
	echo ""
	echo "(c) Copyright 2007 Chris Smith";
	echo "This is free software. You may redistribute copies of it under the terms of";
	echo "the GNU General Public License <http://www.opensource.org/licenses/gpl-license.php>.";
	echo "There is NO WARRANTY, to the extent permitted by law.";
	echo "";
	echo "Written by Chris Smith <http://www.cs278.org/>";
	exit 0;
}

if [ "$1" = "--help" ]; then
	show_usage 0
	exit 0;
elif [ "$1" = "--version" ]; then
	show_version
	exit 0;
fi

STATUS_FILE="dpkg-status";

$TOUCH "$STATUS_FILE" 2>/dev/null || (echo "Failed to create status file!" >&2; \
exit 2);

$CHMOD 0600 "$STATUS_FILE";

$DPKG --get-selections > "$STATUS_FILE"

exit $?
