#!/bin/bash

#
# rsnapshot-backup-dns
#
# (c) Copyright 2007 Chris Smith
# This is free software. You may redistribute copies of it under the terms of
# the GNU General Public License <http://www.opensource.org/licenses/gpl-license.php>.
# There is NO WARRANTY, to the extent permitted by law.
#
# $Id$
#
# Download latest from: $HeadURL$
#

WHICH=$(which which);

if [ "$?" != "0" ]; then
	AWK=/usr/bin/awk;
	DIG=/usr/bin/dig;
else
	AWK=$($WHICH awk);
	DIG=$($WHICH dig);
fi

function show_usage {
	echo "Usage: $0 [ --version | --help | domain ]";
	echo -e "    --help\tDisplay this help and exit";
	echo -e "    --version\tDisplay version and exit";
	exit $1;
}

function show_version {
	echo "rsnapshot-backup-dns";
	echo '$Id$';
	echo ""
	echo "(c) Copyright 2007 Chris Smith";
	echo "This is free software. You may redistribute copies of it under the terms of";
	echo "the GNU General Public License <http://www.opensource.org/licenses/gpl-license.php>.";
	echo "There is NO WARRANTY, to the extent permitted by law.";
	echo "";
	echo "Written by Chris Smith <http://www.cs278.org/>";
	exit 0;
}

if [ "$1" == "--help" ]; then
	show_usage 0;
	exit 0;
elif [ "$1" == "--version" ]; then
	show_version;
	exit 0;
elif [ "$1" == "" ]; then
	show_usage 1;
	exit 1;
else
	DOMAIN=$1;
fi

PRIMARY_NS=$($DIG +short soa $DOMAIN @80.225.250.186 | $AWK '{ print $1; }');

echo -e ";\n; $DOMAIN from $PRIMARY_NS\n;\n" > "$DOMAIN.zone";

echo "; -- BEGIN DATA --" >> "$DOMAIN.zone";
$DIG +noall +answer axfr $DOMAIN @$PRIMARY_NS >> "$DOMAIN.zone";
echo "; -- END DATA --" >> "$DOMAIN.zone";

exit $?;
