#!/bin/sh

#
# rsnapshot-backup-svn
#
# (c) Copyright 2007 Chris Smith
# This is free software. You may redistribute copies of it under the terms of
# the GNU General Public License <http://www.opensource.org/licenses/gpl-license.php>.
# There is NO WARRANTY, to the extent permitted by law.
#
# $Id$
#
# Download latest from: $HeadURL$
#

# Trap ^C
trap 'exit 1' TERM INT;

WHICH=$(which which);

if [ "$?" != "0" ]; then
	CHOWN=/bin/chown
	CHGRP=/bin/chgrp
	CHMOD=/bin/chmod
	FIND=/usr/bin/find
	RSYNC=/usr/bin/rsync
	SED=/bin/sed
	STAT=/usr/bin/stat
	SVN=/usr/bin/svn
	SVNADMIN=/usr/bin/svnadmin
	XARGS=/usr/bin/xargs
else
	CHOWN=$($WHICH chown);
	CHGRP=$($WHICH chgrp);
	CHMOD=$($WHICH chmod);
	FIND=$($WHICH find);
	RSYNC=$($WHICH rsync);
	SED=$($WHICH sed);
	STAT=$($WHICH stat);
	SVN=$($WHICH svn);
	SVNADMIN=$($WHICH svnadmin);
	XARGS=$($WHICH xargs);
fi

is_repository()
{
	if [ -d "$1/db" -a -d "$1/conf" -a -d "$1/hooks" ]; then
		return 1;
	else
		return 0;
	fi
}

get_mode()
{
	$STAT --format=%a $1
}

get_uid()
{
	$STAT --format=%u $1
}

get_gid()
{
	$STAT --format=%g $1
}

backup_repos()
{
	REPOS=$1;

	$SVNADMIN hotcopy "$BASE/$REPOS" "$REPOS";

	$CHOWN $(get_uid $BASE/$REPOS) $REPOS;
	$CHGRP $(get_gid $BASE/$REPOS) $REPOS;
	$CHMOD $(get_mode $BASE/$REPOS) $REPOS;

	# Use hotcopied directory because svnadmin cleans some stuff out ;)
	REPOS_FILES=$($FIND "$REPOS" -print0 | $XARGS -0);

	for REPOS_FILE in $REPOS_FILES; do

		if [ ! -e "$BASE/$REPOS_FILE" ]; then

			# This file (db/format) can be created by
			# hotcopy no worries if it doesn't exist
			# hotcopy sets the correct mode,
			# and ownership should not matter
			# as the repository never writes to it.

			if [ "$REPOS_FILE" != "$REPOS/db/format" ]; then
				echo "$REPOS_FILE does not exist at source." >&2;
			fi

		else

			$CHOWN $(get_uid "$BASE/$REPOS_FILE") $REPOS_FILE;
			$CHGRP $(get_gid "$BASE/$REPOS_FILE") $REPOS_FILE;
			$CHMOD $(get_mode "$BASE/$REPOS_FILE") $REPOS_FILE;

		fi
	done
}

show_usage()
{
	echo "Usage: $0 [ --version | --help | src ]";
	echo -e "    --help\tDisplay this help and exit";
	echo -e "    --version\tDisplay version and exit";
	exit $1;
}

show_version()
{
	echo "rsnapshot-backup-svn";
	echo '$Id$';
	echo ""
	echo "(c) Copyright 2007 Chris Smith";
	echo "This is free software. You may redistribute copies of it under the terms of";
	echo "the GNU General Public License <http://www.opensource.org/licenses/gpl-license.php>.";
	echo "There is NO WARRANTY, to the extent permitted by law.";
	echo "";
	echo "Written by Chris Smith <http://www.cs278.org/>";
	exit 0;
}

if [ "$1" = "" ]; then
	show_usage 1
	exit 1;
elif [ "$1" = "--help" ]; then
	show_usage 0
	exit 0;
elif [ "$1" = "--version" ]; then
	show_version
	exit 0;
fi


BASE=$(echo "$1" | $SED "s,[/]*$,,");

DIRS=$($FIND $BASE -type d -print0 | xargs -0)
REPOSITORIES="";
EXCLUDES="";

for DIR in $DIRS; do

	DIR_REL=$(echo $DIR | $SED "s,$BASE/*,,");

	is_repository $DIR;

	if [ "$?" = "1" ]; then
		REPOSITORIES="$DIR_REL $REPOSITORIES";
		EXCLUDES="--exclude=$DIR_REL/ $EXCLUDES";
	fi
done

$RSYNC -au $EXCLUDES $BASE/ .;

for REPOS in $REPOSITORIES; do

	echo "Backing up $REPOS..."

	backup_repos "$REPOS"

	$SVNADMIN verify $REPOS

	echo "done."
done
