#!/bin/sh

#
# rsnapshot-backup-mysql
#
# (c) Copyright 2007 Chris Smith
# This is free software. You may redistribute copies of it under the terms of
# the GNU General Public License <http://www.opensource.org/licenses/gpl-license.php>.
# There is NO WARRANTY, to the extent permitted by law.
#
# $Id$
#
# Download latest from: $HeadURL$
#

WHICH=$(which which);

if [ "$?" != "0" ]; then
	CHMOD=/bin/chmod;
	GZIP=/bin/gzip;
	MYSQL=/usr/bin/mysql;
	MYSQLDUMP=/usr/bin/mysqldump;
	XARGS=/usr/bin/xargs;
	TOUCH=/usr/bin/touch;
else
	CHMOD=$($WHICH chmod);
	GZIP=$($WHICH gzip);
	MYSQL=$($WHICH mysql);
	MYSQLDUMP=$($WHICH mysqldump);
	XARGS=$($WHICH xargs);
	TOUCH=$($WHICH touch);
fi

show_usage()
{
	echo "Usage: $0 [ --version | --help | cnf_file ]";
	echo -e "    --help\tDisplay this help and exit";
	echo -e "    --version\tDisplay version and exit";
	exit $1;
}

show_version()
{
	echo "rsnapshot-backup-mysql";
	echo '$Id$';
	echo ""
	echo "(c) Copyright 2007 Chris Smith";
	echo "This is free software. You may redistribute copies of it under the terms of";
	echo "the GNU General Public License <http://www.opensource.org/licenses/gpl-license.php>.";
	echo "There is NO WARRANTY, to the extent permitted by law.";
	echo "";
	echo "Written by Chris Smith <http://www.cs278.org/>";
	exit 0;
}

ls_db()
{
	 echo "SHOW DATABASES" | $MYSQL $MYSQL_CNF --batch --silent | $XARGS
}

if [ "$1" = "--help" ]; then
	show_usage 0
	exit 0;
elif [ "$1" = "--version" ]; then
	show_version
	exit 0;
fi

if [ "$1" != "" -a -f "$1" ]; then
	MYSQL_CNF="--defaults-extra-file=$1";
else
	MYSQL_CNF="";
fi

for DB in `ls_db`; do
	echo "Backing up $DB...";

	$TOUCH "$DB.sql.gz" 2>/dev/null || (echo "Failed to create dump file!"; \
	exit 2);

	$CHMOD 0600 "$DB.sql.gz";

	# The likely hood that dumps will be the same is slim,
	# mysqldump puts a timestamp in the file, so I figured
	# it would be better to compress the output.
	$MYSQLDUMP $MYSQL_CNF --tz-utc $DB | $GZIP --best > "$DB.sql.gz"
	echo "Done."
done

exit $?
