Document: cs-meta
Title: Debian cs-meta Manual
Author: <insert document author here>
Abstract: This manual describes what cs-meta is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cs-meta/cs-meta.sgml.gz

Format: postscript
Files: /usr/share/doc/cs-meta/cs-meta.ps.gz

Format: text
Files: /usr/share/doc/cs-meta/cs-meta.text.gz

Format: HTML
Index: /usr/share/doc/cs-meta/html/index.html
Files: /usr/share/doc/cs-meta/html/*.html

  
